version: '2'
services:
  apache_with_php:
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=naukroom
      - MYSQL_USER=naukroom_usr
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysqldumpfolder:/mysqldumpfolder
    ports:
      - "33060:3306"
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db
